# Header
menu:
  Home: /
banner: images/pencilbg.jpg
subtitle: He goes before me, I am merely in His Shadow

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 5
# Footer
copyright: |-
  No parts of the posts here may be reproduced without express permission, which can be obtained at <a href="mailto:blogs@theshadow.xyz">this email</a>
  <br> All content on this site except <a href="/css/images/pencilbg.webp">the banner image</a> are

# Sidebar
sidebar: right
widgets:
- category
- recent_posts

# Miscellaneous
favicon: /favicon.png
